version: '3.7'
services:
  db:
    container_name: uber_eats_db
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ubereats
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  pgadmin:
    container_name: uber_eats_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  postgres_data:
