openapi: "3.0.2"
info:
  title: Uber eats pet project
  version: "0.0.1"
servers:
  - url: https://localhost:8000/
    description: Dev server
paths:
  /test:
    get:
      responses:
        "200":
          description: OK
